---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: public
  rules:
  - host: cradle.nextcloud.ig.ecl.d3d1.de
    http:
      paths:
      - backend:
          service:
            name: example
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - cradle.nextcloud.ig.ecl.d3d1.de
    secretName: ingress-tls
---
apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    app: example
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: example
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example
  labels:
    app: example
spec:
  serviceName: "example"
  replicas: 1
  selector:
    matchLabels:
      app: example
  volumeClaimTemplates:
    - metadata:
        name: example
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10G
        storageClassName: longhorn
        volumeMode: Block
  template:
    metadata:
      labels:
        app: example
    spec:
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
      nodeSelector:
        kr/snp: "v14"
      containers:
      - name: cradle
        image: ctr.0x.pt/kraud/cradle-snp:3c1e2a2-dirty
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "1"
            memory: "3072Mi"
          requests:
            cpu: "1"
            memory: "3072Mi"
        volumeDevices:
        - name: example
          devicePath: /dev/volumes/example
        volumeMounts:
          - mountPath: /dev/shm
            name: shm
        env:
          - name:   POSTGRES_PASSWORD
            value:  fixmeGetFromSecret
        command:
          - cradle
          - run
          - --inline
          - |
            apiVersion: cradle.kraudcloud.com/v3
            kind: CradleLaunchIntent
            spec:
              id: f8b26feb-8997-4ab4-ae74-843b1abd9d44
              resources:
                mem: 1024
                cpu: 1
              volumeDevices:
                - name: example
                  devicePath: /dev/volumes/example
              containers:
                - name: enclaivelet
                  kernelMounts:
                    - hostPath:  /config
                      guestPath: /config
                      readOnly:  true
                  image:
                    ref: harbor.enclaive.cloud/public/enclaivelet
                  process:
                    cmd:
                      - /bin/enclaivelet
                    env:
                      - name: ENCLAIVE_KEYSTORE
                        value: https://vhsm-staging.enclaive.cloud
                      - name: ENCLAIVE_NITRIDE
                        value: https://vhsm-staging.enclaive.cloud
                      - name: ENCLAIVE_PROTOCOL
                        value: sev-snp
                      - name: ENCLAIVE_SOURCE
                        value: test
                      - name: ENCLAIVE_RESOURCE
                        value: test-resource
                      - name: ENCLAIVE_INSTANCE
                        value: test-instance
                  lifecycle:
                    critical: true
                    before:   volumes
                - image:
                    ref: nextcloud:28
                  lifecycle:
                    critical: true
                  process:
                    env:
                      - name: postgres_host
                        value: localhost
                      - name: POSTGRES_USER
                        value: postgres
                      - name: POSTGRES_DB
                        value: postgres
                      - name: OVERWRITEPROTOCOL
                        value: https
                      - name: TRUSTED_PROXIES
                        value: "*"
                      - name: POSTGRES_PASSWORD
                        value: password
                  volumeMounts:
                    - volumeName: example
                      volumePath: /data
                      guestPath:  /var/www/html
                - image:
                    ref: postgres:15.3
                  lifecycle:
                    critical: true
                  process:
                    env:
                      - name: POSTGRES_PASSWORD
                        value: password
                  volumeMounts:
                    - volumeName: example
                      volumePath: /db
                      guestPath:  /var/lib/postgresql/data


