apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    app: example
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: example
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example
  labels:
    app: example
spec:
  serviceName: "example"
  replicas: 1
  selector:
    matchLabels:
      app: example
  volumeClaimTemplates:
    - metadata:
        name: example
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1G
        storageClassName: longhorn
        volumeMode: Block
  template:
    metadata:
      labels:
        app: example
    spec:
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
      nodeSelector:
        kr/snp: "v14"
      containers:
      - name: cradle
        image: ctr.0x.pt/kraud/cradle-snp:3c1e2a2-dirty
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "1"
            memory: "3072Mi"
          requests:
            cpu: "1"
            memory: "3072Mi"
        volumeDevices:
        - name: example
          devicePath: /dev/volumes/example
        volumeMounts:
          - mountPath: /dev/shm
            name: shm
        env:
          - name:   POSTGRES_PASSWORD
            value:  fixmeGetFromSecret
        command:
          - cradle
          - run
          - --inline
          - |
            apiVersion: cradle.kraudcloud.com/v3
            kind: CradleLaunchIntent
            spec:
              id: f8b26feb-8997-4ab4-ae74-843b1abd9d44
              resources:
                mem: 1024
                cpu: 1
              volumeDevices:
                - name: example
                  devicePath: /dev/volumes/example
              containers:
                - name: enclaivelet
                  kernelMounts:
                    - hostPath:  /config
                      guestPath: /config
                      readOnly:  true
                  image:
                    ref: harbor.enclaive.cloud/public/enclaivelet
                  process:
                    cmd:
                      - /bin/enclaivelet
                    env:
                      - name: ENCLAIVE_KEYSTORE
                        value: https://vhsm-staging.enclaive.cloud
                      - name: ENCLAIVE_NITRIDE
                        value: https://vhsm-staging.enclaive.cloud
                      - name: ENCLAIVE_PROTOCOL
                        value: sev-snp
                      - name: ENCLAIVE_SOURCE
                        value: test
                      - name: ENCLAIVE_RESOURCE
                        value: test-resource
                      - name: ENCLAIVE_INSTANCE
                        value: test-instance
                  lifecycle:
                    critical: true
                    before:   volumes
                - name: debug
                  volumeMounts:
                    - volumeName: example
                      volumePath: /data
                      guestPath:  /data
                  kernelMounts:
                    - hostPath:  /config
                      guestPath: /
                      readOnly:  true
                  image:
                    ref: alpine
                  process:
                    cmd:
                      - /bin/sleep
                      - infinity
                  lifecycle:
                    critical: true
